### ISSUE TITLE
MemoryStream disposal

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#1]
The server uses a lot of memorystreams to convert data. 

Perhaps its a good idea to dispose of these after they get used (to prevent memory leaking) as said by @Craftplacer

**Comment by Craftplacer** [comment]
Thought of writing an extension method to get the array and dispose it at the same time with a single function to make it all convenient.

**Comment by Naamloos** [comment]
I'll add it right away

**Comment by Naamloos** [comment]
that's not going to work, memorystreams get used in several different contexts

**Comment by Craftplacer** [comment]
Something like
```cs
var array = memoryStream.ToArray();
memoryStream.Dispose();
return array;```

if you get me

**Comment by Naamloos** [comment]
This will not work, as the data read from / written to stream may differ.

**Comment by Craftplacer** [comment]
.... do you even get what I'm talking about? or do I get what you're talking about?

**Comment by Naamloos** [comment]
I don't think you get what I mean

**Comment by Craftplacer** [comment]
I might type out the whole function
```cs
public static byte[] ToArrayAndDispose(this MemoryStream memoryStream)
{
  var array = memoryStream.ToArray();
  memoryStream.Dispose();
  return array;
}
```

**Comment by Naamloos** [comment]
I resolved this with `using`s. this is up for discussion, but I'll close the issue.

**Comment by Craftplacer** [comment]
Each function that uses MemoryStream.ToArray() should or must use ToArrayAndDispose(). This is likely to affect all PacketData classes.

**Comment by Naamloos** [comment]
Honestly, I think we should stay with `using` blocks. `using` makes sure the object gets disposed even when an exception occurs.

We *could* use dispose, but that would mean we'd have to
```
try{
    // do stuff
}catch(Exception ex){

}finally{

}
```
Which just gets really messy.
