### ISSUE TITLE
Fix commands tests

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#101]
`Commands.TestCommandExec()` fails with an exception:
```
❌ Obsidian.Commands.Framework.Exceptions.InvalidCommandOverloadException : No such overload for command pong
```

It seems that command groups are not registered properly.

**Comment by JeremyEspresso** [comment]
Could I be assigned to this issue?

**Comment by JeremyEspresso** [comment]
After having looked at the issue, it seems that the test in question doesn't have the functionality built in yet that it's testing.

See: [https://github.com/ObsidianMC/Obsidian/blob/ca9c85c77f6336f7d36386aaedd2b0b578d5fb91/Obsidian.Tests/Commands.cs#L25](url)

CC @Naamloos

**Comment by Naamloos** [comment]
The test hasn't been updated when I updated the command framework.. I think

**Comment by Naamloos** [comment]
ohh seems like the functionality is indeed not yet there. 

I'll keep this one open for when I refactor the command framework some more.

**Comment by Tides** [comment]
Closing as this has been fixed.
