### ISSUE TITLE
Allow plugin nuget dependencies

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#102]
Allow Obsidian plugins to have nuget dependencies. They should be correctly:
- detected
- checked for duplicity
- downloaded
- loaded

There might be a problem with versioning?

[Related StackOverflow post](https://stackoverflow.com/questions/55509566/how-to-download-latest-nuget-package-programmatically-in-net-core)
[MSDN](https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk)

**Comment by Craftplacer** [comment]
Is it required though? I mean, we could load foreign assemblies (DLLs) too that the user installs part of a plugin. They should only be loaded if the assembly is being depended upon by another plugin.

I can only imagine being useful if the user loads a "source code" plugin.

**Comment by Seb-stian** [comment]
"Source code" plugins are the main target of this issue.

**Comment by Naamloos** [comment]
In all honesty, don't source code plugins have like- a security concern?

**Comment by Seb-stian** [comment]
Don't all of them?

**Comment by Seb-stian** [comment]
Well, at the moment, the way we deal with malicious code is that we disallow referencing certain assemblies. I don't know if it's possible to, for example, remove local files without `System.IO`, `System.Reflection` or `System.Runtime.InteropServices` (or other assembly that references those). We can still provide all the functionality via services, but without security risks, that's the idea. However, I don't call myself a security expert, so my thinking may be flawed.

In the past I've worked on other projects involving uMod, which is doing something [similar](https://umod.org/documentation/api/security). I think that they used Regex on the source code, to detect if any blacklisted namespaces were present, but the implementation is not as important here.

**Comment by Seb-stian** [comment]
@Naamloos Maybe you could add "Server development" category to GitHub discussions and open "Plugins security concerns"? Or just open another issue specifically for it.

**Comment by roxxel** [comment]
can i get assigned to this issue?

**Comment by Tides** [comment]
Closing this as it was done with #436
