### ISSUE TITLE
Update to .NET 6

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#124]
During November this year (11/2021), new version of .NET will get released. We should update to make use of its performance improvements, new features and LTS.

- [x] Update all project files `net5.0` → `net6.0`
- [x] Update project description (About, README, csproj...) `.NET 5` → `.NET 6`
- [x] #125
- [x] #126
- [x] #173 
- [x] #174

**Comment by Seb-stian** [comment]
After reconsideration, we shouldn't wait for the full release and go with RC1 (should come out in September).

**Comment by Naamloos** [comment]
Considering we're only entering prerelease soon ourselves there's no need to use stable .NET versions. Using prerelease should be fine for now I think. Especially considering the cool new features we can use.

**Comment by Czompi** [comment]
I can start the migration, most of my projects, that I recently worked on using .NET 6.0, so I gained a bit of experience of the new features.

**Comment by Seb-stian** [comment]
@Czompi Awesome. Do you want the whole thing, or some specific issues?

**Comment by Czompi** [comment]
I've not used the new math APIs yet and iirc the STJ part is done(?), so I'll try to do the first 2 tasks.

**Comment by Seb-stian** [comment]
> iirc the STJ part is done(?)

We fully migrated to STJ, but .NET 6 brings new features to it. The one I'm interested in is source generators. You can learn more [here](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/).

**Comment by Naamloos** [comment]
🎉 .NET 6 is out! time this issue and others that are related will get the `priority: medium` tag and lose the `future` tag!

**Comment by Naamloos** [comment]
Closing this issue, as the last remaining task has it's own issue.
