### ISSUE TITLE
Packet interrupting for plugins

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#13]
An idea that might be interesting for plugins is adding support for interrupting packets.

My idea of how to implement such a thing:
events. We could have an event that the packet handler passes packets through before sending them, where plugins can choose to modify some values.

**Comment by Naamloos** [comment]
The event task gets awaited before sending off the actual packet.

**Comment by Craftplacer** [comment]
```cs
Server/PacketHandler.PacketIncoming(PacketIncomingEventArgs eventArgs)
eventArgs.Cancel = true; //will stop the server from processing
eventArgs.Packet.Something = null;
```

```cs
Server/PacketHandler.PacketOutcoming(PacketOutcomingEventArgs eventArgs)
eventArgs.Cancel = true; //will stop the server from sending it out
eventArgs.Packet.Something = null;
```

**Comment by Naamloos** [comment]
something like that, yeah

**Comment by Naamloos** [comment]
edited your comment for github fucking up markdown

**Comment by Tides** [comment]
Done in https://github.com/Naamloos/Obsidian/commit/11ca2d9b8cab63adce97736b6edc99b692190cc3
If you have any objections to it re-open the issue 👀
