### ISSUE TITLE
Make object initializers consistent.

### ISSUE THREAD

**Issue by tacosontitan** [ObsidianMC/Obsidian#144]
When instantiating objects and setting members simultaneously, it can be seen that there are two ways of doing this (sometimes in the same file:
```
var x = new Something() { Foo = 3 };
var y = new Something { Foo = 3 };
```
Both are perfectly acceptable, but mixing and matching should be avoided.

**Comment by Naamloos** [comment]
Though this will not really have any performance impacts, it is important to be consistent throughout the project, yes. Thank you for your suggestion :)

**Comment by Craftplacer** [comment]
Is a `.editorconfig` rule applicable here?
