### ISSUE TITLE
"privacy" mode

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#153]
I was watching a FitMC video about jeb_ being griefed because some custom server indexer found the server he was playing on. This made me think it might be a good idea to add a "privacy" mode next to the whitelist, where the server will not return online player names after being queried.

Video in question: 
https://www.youtube.com/watch?v=fvbVnT-RW-U

This is just an idea, but I think it might be nice to have. Maybe even a super private mode that wouldn't even return queried server info, whatever. I just think it would be nice and interesting. Let me know.

**Comment by Naamloos** [comment]
A bit more into the technical specifics: When a server's status is being queried by the game it returns a ping, an MOTD, a server icon, the player list and the (max) amount of online players.

**Comment by Craftplacer** [comment]
Interesting idea, we might be able to take it further and build a "better" whitelist though.

For example, if we receive a connection, we could do IP based whitelisting and drop the connection immediately (no packet transfer, immediately close the connection) when it tries to connect.

Furthermore we should include an option to disable querying of the server all together like you sort of suggested (maybe make different levels starting from "Full", "Anonymized" (no names, count, etc.) and "None" (make server appear dead or incompatible).

**Comment by Naamloos** [comment]
All very nice ideas that I really like.

**Comment by Naamloos** [comment]
for anyone coming here through hacktoberfest: this might be a nice issue to tackle if you feel like it! :3

**Comment by Naamloos** [comment]
Part of this issue has been implemented. 

It might be nice to add an option hiding online count, but keeping max player count intact. If anyone wants to tackle that for hacktober, be my guest.

**Comment by ndelta0** [comment]
> Furthermore we should include an option to disable querying of the server all together like you sort of suggested (maybe make different levels starting from "Full", "Anonymized" (no names, count, etc.) and "None" (make server appear dead or incompatible). 

Notchian server already has that option, it's called `enabled-status`.

**Comment by Naamloos** [comment]
> 
> 
> > Furthermore we should include an option to disable querying of the server all together like you sort of suggested (maybe make different levels starting from "Full", "Anonymized" (no names, count, etc.) and "None" (make server appear dead or incompatible).
> 
> Notchian server already has that option, it's called `enabled-status`.

I just added it in my most recent PR.

**Comment by Naamloos** [comment]
Opening new issues for stuff I missed in the initial PR.
