### ISSUE TITLE
NullReferenceException on Held Item Change

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#160]
During playtesting, moving an item around inventory, an exception was thrown.

[Location](https://github.com/ObsidianMC/Obsidian/blob/bb4a0954b744231de6c315b848a8d746378386aa/Obsidian/Net/Packets/Play/Serverbound/ServerHeldItemChange.cs#L22)

`Player.GetHeldItem` can return `null`, but the method's return type is not marked as nullable (even though `Inventory.GetItem` which it wraps around has nullable return type). `heldItem` being `null` then causes an exception, as its properties are being accessed.

*This should be an easy fix, but I would also like to note that we clearly haven't fully used the nullable notation and we should. Perhaps we could set nullable warnings as errors (`<WarningsAsErrors>Nullable</WarningsAsErrors>`) to enforce null-safety? Related: #98*

**Comment by Tides** [comment]
I noticed this problem on my inventory branch and realized the object is basically being copied instead of being supplied straight through. I'm not sure if it was changed before but it should be supplied straight through imo ~ And I'm indifferent about enforcing nullable warnings as errors

**Comment by Tides** [comment]
Fixed in 154eb33b2570c6815e4fa7ffdbfae32dd42c87bd 🙏🏼
