### ISSUE TITLE
Resolve major warnings by GH actions compiler

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#163]
Builds generated by GitHub produce some warnings. these need to be fixed. Check the actions tab for output. Any xmldoc issues that nag about non-existant docs can be ignored for now.

**Comment by HenryMigo** [comment]
I can pick this one up

**Comment by HenryMigo** [comment]
It seems a lot of the warnings could be solved with constructors within the models. Could take a while to implement these constructors.

EDIT: It also looks like the build only shows the top 10 warnings. If this is correct then you've got around 3791 warnings to resolve. What I suggest is we eliminate these warnings in small batches to avoid thousands of changes. @Seb-stian do you agree with this approach?

**Comment by Naamloos** [comment]
Do note that I was referring to the warnings given by github. Warnings by vs/the compiler are of course still welcome to be resolved.

**Comment by HenryMigo** [comment]
> 
> 
> Do note that I was referring to the warnings given by github. Warnings by vs/the compiler are of course still welcome to be resolved.

It looks like it is the compilers warnings in VS but only the top 10 of these as if you drill into the build task in Actions it shows you all the warnings.

**Comment by Naamloos** [comment]
> > 
> > 
> > Do note that I was referring to the warnings given by github. Warnings by vs/the compiler are of course still welcome to be resolved.
> 
> It looks like it is the compilers warnings in VS but only the top 10 of these as if you drill into the build task in Actions it shows you all the warnings.

Ahh, fair. I haven't looked into them that much yet 😅

**Comment by HenryMigo** [comment]
I'll try and tackle as much as I can but don't want to touch too many files in one go.

**Comment by HenryMigo** [comment]
Just a question, I am seeing async methods around the code that do not have awaitable code within them, do these need to be async and if so `await Task.Run(() => OUR_CODE);` will need to be used.

**Comment by Seb-stian** [comment]
Yes, we do have fire-and-forget tasks here and there. The point is to have some code execute on a thread pool, while execution of the calling code continues.

**Comment by Seb-stian** [comment]
Also sorry, didn't notice the edit before. That approach sounds reasonable.

**Comment by HenryMigo** [comment]
I think I have managed to solve a few, most are XML warnings. 3692 relate to XML out of the 3708 while there are 16 other warnings. PR is #168

**Comment by Naamloos** [comment]
I'll probably look into muting the "missing xmldoc" warnings project-wide sometime soon.
