### ISSUE TITLE
Point of "Operator Requests"?

### ISSUE THREAD

**Issue by ndelta0** [ObsidianMC/Obsidian#172]
What was the idea behind making operator requests? Seems pointless as no server would have that enabled and even if it did, there would be a lot spam and/or bruteforcing the codes to get become an operator.

**Comment by Craftplacer** [comment]
It was added by me back then, supposed to be a simple way to OP yourself without having to edit the config or having to type something into the console (which is still something that doesn't work to this day IIRC).

**Comment by Craftplacer** [comment]
It may be food for thought to extract it into a separate plugin when executing commands in the main server console becomes possible.

**Comment by Naamloos** [comment]
the "operator request" feature is just named poorly. It's a simple system that allows you to get op via a code in console 👍

**Comment by Tides** [comment]
Closing as this question was answered.
