### ISSUE TITLE
Refactor throwing ArgumentNullException

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#173]
With .NET 6, this code

```cs
if (foo is null)
    throw new ArgumentNullException(nameof(foo));
```

can be replaced by

```cs
ArgumentNullException.ThrowIfNull(foo, nameof(foo));
```

which is to be prefered.

**Comment by Craftplacer** [comment]
Wasn't it possible before to `Property = argument ?? throw new ArgumentNullException(nameof(argument));`?

**Comment by Seb-stian** [comment]
> Wasn't it possible before to `Property = argument ?? throw new ArgumentNullException(nameof(argument));`?

Yes it was, but when simply null-checking method arguments, you would have to do something like
```cs
_ = arg ?? throw new ArgumentNullException(nameof(arg));
```

**Comment by Craftplacer** [comment]
I guess [that pattern](https://github.com/ObsidianMC/Obsidian/issues/173#issuecomment-962497759) stays constructor-exclusive for now.
