### ISSUE TITLE
Bukkit plugin interop

### ISSUE THREAD

**Issue by Craftplacer** [ObsidianMC/Obsidian#18]

**Comment by Naamloos** [comment]
:)

**Comment by Craftplacer** [comment]
Delayed until .NET 5's announced Java Interop feature.

**Comment by Naamloos** [comment]
.Net 5 has no java interop, it is expected for .NET 6,which releases in 2021

**Comment by Aaron2550** [comment]
As far as [this post](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/#comment-8551) states, “Java interoperability” basically means being able to use the Java.Interop namespace on the desktop. Maybe someone could check the [API](https://docs.microsoft.com/en-us/dotnet/api/java.interop?view=xamarin-android-sdk-9&viewFallbackFrom=xamarin-android-sdk-11) to see if what we want to do is actually possible?

**Comment by Tides** [comment]
Closing since we won't be trying to implement this anymore.
