### ISSUE TITLE
[ Idea ] [ very cool! ] Splitting up communication and behavior code

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#182]
This would take a lot of work to actually get set up properly, but it would allow us to very easily create different implementations of behavior for the server. 

for example:
- Proxy server that doesn't need world gen, AI, all the other fancy stuff
- Proxy server (again) that logs packets between a server and a client for research purposes
- Empty server that just displays the title "poop" over and over because why the hell not? 😆

**Comment by Aaron2550** [comment]
why not just make the two proxy servers one big thing? "debug releases" log things, "release releases" just dont?

**Comment by Naamloos** [comment]
the one is a "bridge" between two (or more) servers, while the other would be a tool for packet analysis.. quite a difference imho

**Comment by Aaron2550** [comment]
The proxy is never between servers. It is always between clients and one or multiple servers. In a production environment nobody should need packet logging, while in a test environment where debug builds are "more useful" you'd probably want the packet logging because well.... You are in a test environment so u wanna test stuff. While I'm not for or against two proxy repos with different uses, I think this approach would/could probably save some duplicate code..

**Comment by Naamloos** [comment]
the proxy does not connect clients. it connects servers. Allows a client to hop between them.

As for packet logging, I still think it should be a separate application, as it does not need the fancy server switching stuff that e.g. bungeecord would be used for. Both are proxies, but with different use cases.

**Comment by Craftplacer** [comment]
So decouple handling packets and running game logic into two separate things so you'd have an easier time changing it?

**Comment by Craftplacer** [comment]
I can imagine it going this way: we define a simple abstract PacketHandler class, which can be inherited by many classes, I'd say you'd just write a default "AuthenticationPacketHandler" with events for handling various auth things.

**Comment by Aaron2550** [comment]
A Proxy does not connect Servers. All Clients connect to the Proxy and then the Proxy logs the Players in and out of the Servers it is responsible for/connected to. Example: Lets say you are Hypixel and your Lobby-1 Server goes down. What makes more sense? What im describing on the Left or what youre describing on the Right?
![image](https://user-images.githubusercontent.com/24834067/141677286-0df30bc2-8030-441e-8817-686fef52d119.png)

**Comment by Naamloos** [comment]
First one, but a server can send the client "back" to the proxy (via plugin) to join another one

**Comment by Aaron2550** [comment]
the proxy just logs the palyer out of server1, sends a "teleporting to another world" packet so the client shows the "loading world" screen and then logs the player in on server2

**Comment by Naamloos** [comment]
😐 the specifics aren't really that important here imo

**Comment by Naamloos** [comment]
Same ideas are being proposed in #185. I'll close this issue as seb's wording is just infinitely better than what I did here.
