### ISSUE TITLE
Add global usings

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#186]
I suggest adding `global using`s for the following:
- `System`
- `System.Linq`
- `System.Collections.Generic`
- `static` `Obsidian.Utilities.Extensions`

Other candidates:
- `System.Collections.Concurrent`
- `System.Threading.Tasks`
- `Obsidian.API`

**Comment by Jonpro03** [comment]
Great idea. I'm okay with also adding Obsidian.API, but not sure on the threading ones...

**Comment by Naamloos** [comment]
I think Tasks is a great one imo, we make heavy use of TAP

**Comment by Tides** [comment]
I agree I think we should add all of them as global usings since they're all consistently used throughout the project
