### ISSUE TITLE
'libhostpolicy.so not found' error when running latest github actions build

### ISSUE THREAD

**Issue by ghost** [ObsidianMC/Obsidian#199]
Downloading and running the build from [this Actions run](https://github.com/ObsidianMC/Obsidian/actions/runs/1607896091) shows the following error:

```
❯ dotnet Obsidian.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/spiral/mc/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/home/spiral/mc/Obsidian.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/home/spiral/mc/Obsidian.runtimeconfig.json' file and specify the appropriate framework.
```

I'm running dotnet 6.0.100 on PopOS

**Comment by Seb-stian** [comment]
Nightly builds don't seem to contain `Obsidian.ConsoleApp.exe`, which is the new Obsidian front-end. `Obsidian.dll` is a class library containing implementation of the server, but it can't be executed by itself.

**Comment by Seb-stian** [comment]
I'd assume the problem is [here](https://github.com/ObsidianMC/Obsidian/blob/4be11ffb8dc81835ba5c5e5c1e988995afd3da0b/.github/workflows/dotnet.yml#L28). The solution should be to change the path to the bin folder of `Obsidian.ConsoleApp`.
