### ISSUE TITLE
Remove Azure Pipelines

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#200]
See [azure-pipelines.yml](https://github.com/ObsidianMC/Obsidian/blob/4be11ffb8dc81835ba5c5e5c1e988995afd3da0b/azure-pipelines.yml#L14).

We should update them to .NET 6.

**Comment by Naamloos** [comment]
pretty sure I swapped azure pipelines for github actions

**Comment by Seb-stian** [comment]
Close the issue and open another one: "Remove azure-pipelines"?
