### ISSUE TITLE
Make source generators incremental

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#205]
> [...] the source generator will not scale to large projects without migration to the v2 (incremental) API.
> -.NET Team

SyntaxReceiver walks through all syntax trees every time source generators are invoked, which is VERY often. This can lead to a very bad development experience, your IDE may even hang. This problem occurs with larger repositories, which Obsidian is going to be at some point. The new APIs solve this performance problem.

**Comment by Tides** [comment]
Closing this as its been done~
