### ISSUE TITLE
Network-based whitelisting

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#224]
As suggested in #153, IP whitelists might be nice to have. This means immediately blocking when an incoming IP is not whitelisted, not even advertising the fact the port belongs to a minecraft server (unless you're whitelisted, of course.)

priority is low, but it's really nice to have some low level whitelisting

**Comment by roxxel** [comment]
Can I be assigned to this issue?

**Comment by Naamloos** [comment]
@roxxel Sure. Feel free to use the config.json file for the ip whitelist.

**Comment by Czompi** [comment]
This feature could add support for dynamic IPs with ddns (I mean *add domain support alongside IPs*).

**Comment by roxxel** [comment]
> This feature could add support for dynamic IPs with ddns (I mean _add domain support alongside IPs_).

Could u explain what u mean?
