### ISSUE TITLE
Google search results preview typo

### ISSUE THREAD

**Issue by BTELNYY** [ObsidianMC/Obsidian#247]
Just odd, I do not know if this is Google's issue or something with this repo
![Screenshot 2022-02-25 213647](https://user-images.githubusercontent.com/74313030/155827451-5db30408-cbdd-469a-b542-a223772cdc3c.png)

**Comment by Naamloos** [comment]
This is not something we can fix unfortunately. That typo does not actually exist on our repository.

**Comment by Seb-stian** [comment]
We could try to request Google to re-index the site.
