### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by zptr1** [ObsidianMC/Obsidian#25]
Since GPL license is dissalows closed-source projects, GPL license may cause inconvenience for developers that make private projects, and this may affect on Obsidian's popularity. So, please, change Obsidian's license to MIT.

**Comment by roxxel** [comment]
yep, devs should change license to MIT or something (maybe wtfpl or apache 2)

**Comment by zptr1** [comment]
Closing issue because it was created with a reason about private plugins, but as it turned out later, plugins is seperated from Obsidian
