### ISSUE TITLE
Update to preview versions of .NET

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#261]
Before the first official Obsidian release, we can make use of preview .NET technologies. There is no reason not to, as we don't have any end-customers who may suffer from instability. This will help us to keep up with the newest features as they come out, instead of doing bulk updates yearly.

Currently this means updating to .NET 7 Preview 3

**Comment by Seb-stian** [comment]
@Naamloos Any further suggestions of what should be done after updating?

- use Regex source generators
- fix possible [breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/7.0)
- ...

**Comment by Naamloos** [comment]
Honestly I'm not too sure lol

But being up to date is always fun

**Comment by Seb-stian** [comment]
No longer relevant
