### ISSUE TITLE
Console.ReadKey() blocking the entire server in Linux

### ISSUE THREAD

**Issue by GasInfinity** [ObsidianMC/Obsidian#264]
While testing the server for the first time on a Linux PC, I found a bug. 

When the console app waits for a keypress, the entire server blocks and doesn't log anything or send any packets to the client until the enter key is pressed (one or multiple times).
![image](https://user-images.githubusercontent.com/58077502/169083436-03bcc25d-a818-4047-9e9f-fc6f34e38c16.png)

If no one is against it, I'll make a pull request now with the fix.

<sub>Sorry for my bad English, I'm not a native speaker<sub>

**Comment by Seb-stian** [comment]
Thank you for opening the issue. I believe this is a known problem with [ConsoleIO](https://github.com/ObsidianMC/Obsidian/blob/master/Obsidian/Utilities/ConsoleIO.cs) and setting `BasicIO` to `true` should fix it. Feel free to open a PR.

I would imagine something like this to work, but I haven't tested it:
```cs
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    ConsoleIO.BasicIO = true;
}
```
