### ISSUE TITLE
Allow plugins to access player IPs

### ISSUE THREAD

**Issue by Craftplacer** [ObsidianMC/Obsidian#266]
From [the discussion over at our discord server](https://discord.com/channels/772894170451804220/772894251678695495/998804883593498736).

Currently it doesn't seem like we allow plugins to get IPs of players.

My additional thought might be to disallow plugins to get IPs by default, and making this a permission to give to plugins, but that would probably require another system to be in place to make this happen in the first place.

**Comment by roxxel** [comment]
Can I get assigned for this issue?

**Comment by Craftplacer** [comment]
Done

**Comment by Naamloos** [comment]
Sure
