### ISSUE TITLE
Biome Colors broken

### ISSUE THREAD

**Issue by Aaron2550** [ObsidianMC/Obsidian#268]
The first block that gets placed after server start has biome colors, all other placed blocks dont have biome colors and are white. After rejoining even the first block which had color is white now.

After server start + join:
![image](https://user-images.githubusercontent.com/24834067/179781773-32f65f97-a63b-4453-b3f9-b7a49a1e1e4d.png)

After rejoin:
![image](https://user-images.githubusercontent.com/24834067/179781737-73b3bb92-0a13-4aa4-a57b-438acec4e329.png)

**Comment by Tides** [comment]
Closing this as I believe its been fixed.
