### ISSUE TITLE
Fail to lstat a symbolic link file when opening obsidian

### ISSUE THREAD

**Issue by Ryokki** [ObsidianMC/Obsidian#273]
When I open Obsidian, there is such a error below: 
![image](https://user-images.githubusercontent.com/64571933/182036897-673f03ca-9193-49de-b96f-b59194cc6741.png)

I noticed that the file test is a symbolic link file, and I tested adding a symbolic link file to a working vault and found the same error, so this is a must-present question when here is a symbolic link file.

**Comment by Aaron2550** [comment]
Probably a problem with https://obsidian.md/ and not this Project
