### ISSUE TITLE
Make /time command behave like vanilla

### ISSUE THREAD

**Issue by Craftplacer** [ObsidianMC/Obsidian#282]
- [ ] It does not have `set`, `add` sub-commands, but can only set a certain time (It only works like `/time set`)
- [ ] The command does not add the number of days to Day (Days through F3)
- [ ] If you write a number greater than Int32.MaxValue, the command will return an error only to the console.
- [ ]  If no time was provided, the time will be set to 1337 instead.

**Comment by Qialet** [comment]
The message about 1337 was more like finding an easter egg, please leave it)

**Comment by Naamloos** [comment]
Thanks for opening the issue craft <3

**Comment by ghost** [comment]
World's total time is a different task, doesn't depend on the /time command. The overflow is also done separately, commands do not handle that in Obsidian as I understand, they just get values in arguments, if it's overflowing they get nothing.
