### ISSUE TITLE
Rewrite keep alive logic

### ISSUE THREAD

**Issue by OoLunar** [ObsidianMC/Obsidian#291]
As it currently stands, Obsidian can handle the login and play client states, keeping the player online through the keep alive. While the keep-alive logic isn't "broke" per se, it's incorrectly implemented:

> The server will frequently send out a keep-alive, each containing a random ID. The client must respond with the same payload (see serverbound Keep Alive). If the client does not respond to them for over 30 seconds, the server kicks the client. Vice versa, if the server does not send any keep-alives for 20 seconds, the client will disconnect and yields a "Timed out" exception.

> The Notchian server uses a system-dependent time in milliseconds to generate the keep alive ID value. 

https://github.com/ObsidianMC/Obsidian/blob/c38662b4f35e979a4584a7184ab82cd1acc7a211/Obsidian/Client.cs#L468-L470

https://github.com/ObsidianMC/Obsidian/blob/c38662b4f35e979a4584a7184ab82cd1acc7a211/Obsidian/Server.cs#L663

If we take a look here at these two code examples, we can see that the method takes a `long` as [the protocol states](https://wiki.vg/Protocol#Keep_Alive_.28clientbound.29), however, it will cast the result of the subtraction to an `int`. Under perfect circumstances, this will not be an issue as the server ensures that the ids generated will always remain below `1000` and the client is intended to return the id received. However, through the use of mods, the id can be modified and return a number between `int.MaxValue` and `long.MaxValue`, which will cause an exception to be thrown. It is speculated that the server will catch the exception and handle it silently, however in the event that it does not, we can consider this to be an attack vector.

I believe the correct solution is to use Unix timestamps with millisecond precision (`DateTimeOffset.Now.ToUnixTimeMilliseconds()`) for the keep-alive id. A unix timestamp still fits in the range of `long`, prevents duplicate packet ids, and still allows us to track the player's ping.

**Comment by Aaron2550** [comment]
Should we maybe use `DateTimeOffset.UtcNow` instead of `DateTimeOffset.Now`? Daylight saving time would probably break that otherwise, no?

**Comment by OoLunar** [comment]
Unix timestamps are unaffected by timezones and by proxy, daylight savings too

**Comment by Aaron2550** [comment]
> DateTimeOffset.Now uses TimeZoneInfo and caches the timezone on startup.

NVM then, doesnt matter

**Comment by Naamloos** [comment]
I wouldn't exactly call our implementation incorrect either, as it's up to the server when to kick out a player. I'd rather call our implementation "inconsistent with vanilla behavior" which in my opinion is still something worth resolving.

**Comment by Naamloos** [comment]
Assigning to self as I'm toying with this issue rn
