### ISSUE TITLE
Windows terminal weird console output

### ISSUE THREAD

**Issue by XanderStoffels** [ObsidianMC/Obsidian#296]
Maybe this is only a local issue for me, but I get weirdly formatted output if I run Obsidian from a Windows Terminal.

![image](https://user-images.githubusercontent.com/15852653/196116252-0a43a7e1-108f-4217-a772-ac2f880b80f1.png)

**Comment by Naamloos** [comment]
It's not necessarily a Windows Terminal Issue. This happens for me when using `dotnet run`, but it doesn't happen when clicking `Start Debugging` in Visual Studio.

Also doesn't seem to happen anywhere else. Is this issue on us?

**Comment by XanderStoffels** [comment]
Yeah you're right. Only happens with `dotnet run`. Ill check some more.

**Comment by Naamloos** [comment]
Okay I did a quick small test and it appears this issue is specific to Powershell (which is the default backing shell for Windows Terminal).

This seems to be caused by the TPS counter.

**Comment by XanderStoffels** [comment]
It also happens to me on a regular old cmd window.

**Comment by Naamloos** [comment]
oopsie

**Comment by Tides** [comment]
I tested this and the problem no longer seems to be occurring will be closing this issue.
