### ISSUE TITLE
In Code block for C# the syntax highlight don't work in reading view mode

### ISSUE THREAD

**Issue by oaSakamoto** [ObsidianMC/Obsidian#301]
In edit mode, Code block for C# works fine, but when toggle for reading view mode, the syntax highlights don't work more for C#

Edit mode:
![edit_mode](https://user-images.githubusercontent.com/28707205/196327730-6d05b521-7262-4492-8cf8-655181970d98.png)

Reading View mode:
![reading_view](https://user-images.githubusercontent.com/28707205/196328047-24d673ab-cd52-4cc0-925f-9ff60ba4b6a1.png)

**Comment by OoLunar** [comment]
I think this is more of an issue with your editor than our markdown... Is this a markdown file related to Obsidian?

Regardless, try changing `C#` to `cs`. Hopefully that should fix your problem

**Comment by oaSakamoto** [comment]
Thank's Lunar, this worked for me!

**Comment by Naamloos** [comment]
@oaSakamoto We are not Obsidian.md. That is a different project. We make minecraft servers, not markdown editors.

Obsidian has no github repo as it's not open source. Go here: https://obsidian.md/community

**Comment by oaSakamoto** [comment]
@Naamloos I'm sorry for that, my mistake!
