### ISSUE TITLE
chat signing from 1.19.2

### ISSUE THREAD

**Issue by rom1504** [ObsidianMC/Obsidian#304]
hey do you have that new chat signing mecanism from 1.19.2 ? if yes could you point to the place of your code doing it ?
that'd be appreciated thanks

**Comment by Naamloos** [comment]
I don't think we sign / verify signed messages at this point. There may be a branch that has a basic implementation, but not on the master branch.

Along with that, once we do get around to implementing it we intend to allow server admins to disable it without any server plugin required.

**Comment by TheBrambleShark** [comment]
If/when we add it, chat signing should be opt-in rather than opt-out due to the privacy concerns related to the system.

**Comment by Tides** [comment]
Closing this as the question was answered.
