### ISSUE TITLE
Using tailwind for styling?!

### ISSUE THREAD

**Issue by mkal1375** [ObsidianMC/Obsidian#308]

**Comment by OoLunar** [comment]
Hello! It appears you've found the wrong repository. This project is for the Obsidian Minecraft server. What you're looking for is the Obsidian markdown editor. You might be able to find more support on their website: https://obsidian.md/

**Comment by mkal1375** [comment]
so

**Comment by Aaron2550** [comment]
Second time! i Call dibs because i did on the first one too! :D

**Comment by mkal1375** [comment]
Sorry about that 🤣

**Comment by OoLunar** [comment]
No worries!
