### ISSUE TITLE
attachment file not show in the search result.

### ISSUE THREAD

**Issue by xvusrmqj** [ObsidianMC/Obsidian#309]
when use `keyword` search. matched markdown files show in the search result list, but the doc, pdf, xls files not. 

when use `file:keyword` search. both markdown files and the attchment files (doc, pdf, xls ...) show .

**Comment by OoLunar** [comment]
Hello! It appears you've found the wrong repository. This project is for the Obsidian Minecraft server. What you're looking for is the Obsidian markdown editor. You might be able to find more support on their website: https://obsidian.md/
