### ISSUE TITLE
[Discussion] What to do with NibbleArray?

### ISSUE THREAD

**Issue by Seb-stian** [ObsidianMC/Obsidian#332]
There is a class `NibbleArray` residing in `Obsidian.Utilities.Collection` today. The class is not used anywhere. I tracked down its origin to a [gist](https://web.archive.org/web/20151022210950/https://gist.github.com/SirCmpwn/17f848aa8ae87da7427f) linked on [wiki.vg](https://wiki.vg/Code_Snippets). Description on wiki.vg states: *Nibble array storage for chunk metadata, block light, sky light, etc*. Regarding lighting, we use byte arrays directly in [ChunkSection](https://github.com/ObsidianMC/Obsidian/blob/040261df56c21e55a8e879eb1a74d4aff20b73ba/Obsidian/ChunkData/ChunkSection.cs#L23).

My suggestion is to either:
- Remove `NibbleArray.cs` (no more changes needed)
or
- Refactor `NibbleArray` to fix extra overhead and abstraction leak, then use it where applicable

**Comment by Craftplacer** [comment]
I believe this is an essential array class to have for the future. So I opt for refactoring it and providing it for future-use.

**Comment by Tides** [comment]
I also opt in for refactoring ^ ^

**Comment by Jonpro03** [comment]
What is dead may never die? I don't think so... 
We should remove unutilized code. If we ever need it in the future, it's in git history.

**Comment by Tides** [comment]
Removed in #403
