### ISSUE TITLE
Cancellable Events Can Be Uncancelled

### ISSUE THREAD

**Issue by TheBrambleShark** [ObsidianMC/Obsidian#342]
As it stands currently, the `Cancel` property of `ICancellable` is able to be set by any plugin. This creates a possible scenario where a plugin could un-cancel an event, which may cause unexpected behavior.

The `ICancellable` interface should be replaced with an abstract class which handles the cancel logic safely:
```cs
public abstract class CancellableEvent
{
    // Gets a value indicating whether the event has been cancelled.
    public bool IsCancelled { get; private set; }

    // Sets a flag which prevents default (vanilla) behavior from executing.
    public void Cancel()
        => IsCancelled = true;
}
```

**Comment by Tides** [comment]
I believe we had a discussion about this in the discord a while back! Its a good idea if you want to handle it let me know if not then I'll take care of it~
