### ISSUE TITLE
[Proposal] Upgrade Event System

### ISSUE THREAD

**Issue by TheBrambleShark** [ObsidianMC/Obsidian#344]
@Seb-stian was mentioning wanting to do some work on the event system with the goals of making it more robust and removing the potential for typos that come with our current implementation. This issue will act as a proposal for a new event system.

**New Types**
```cs
// A generic EventHandler which returns nothing and accepts event args.
public interface IEventHandler<TEventArgs>
{
    ValueTask Handle(TEventArgs event, CancellationToken cancellationToken);
}

// A base EventHandler. The Handle task should handle some base debug logging and time the execution duration of the handler.
public abstract class EventHandler<TEventArgs> : IEventHandler<TEventArgs>
{
    ValueTask Handle(TEventArgs event, CancellationToken cancellationToken);
    
    abstract ValueTask HandleAsync(TEventArgs event, CancellationToken cancellationToken);
}
```

**Example Implementation**
```cs
// Event Handler
// Notification types are essentially our existing *EventArgs types, but as records.
public sealed class MessageCreatedHandler : EventHandler<ChatMessageCreatedNotification>
{
    public override ValueTask HandleAsync(ChatMessageCreatedNotification event, CancellationToken cancellationToken)
    {
        event.SetHandled();
        // TODO: Get current channel for player, send message to those watching channel
    }
}

// Event Registration
// The OnLoad method is now less of an "event" and now just something called directly during the setup stage for the plugin. It lives as an abstract method in PluginBase and if not overridden it simply returns Task.CompletedTask.
public override Task OnLoad(IServer server)
{
    // Designed to feel like a service registration. First type parameter indicates the type of notification being responded to.
    // The second type parameter indicates the type of handler to generate.
    // If the EventHandler is specified as a type parameter, it must have either no ctor or a public parameterless ctor.
    // Services can be injected into the EventHandler using the InjectAttribute if necessary.
    server.RegisterEventHandler<ChatMessageCreatedNotification, MessageCreatedHandler>();

    // Much like service registration, an instance of a handler which handles the notification specified in the type parameter may be provided. This allows the consumer to pass in things like json configurations, services, or other appropriate items.
    var complexHandler = new SomeComplexHandler(server.Configuration);
    server.RegisterEventHandler<SomeNotification>(complexHandler);
}
```
On the back-end, if an event is not manually registered (or perhaps registered through a function that reflects on the assembly to find instances of `IEventHandler<>`), then it doesn't get added.

This will allow the current MinecraftEventHandler and AsyncEvent types to be reused with some minor alterations and enable plugins to register their own event handlers which can live in their own classes outside of the plugin class.

### Known Issues/Things to Address
* Registration Safety - How do we prevent plugins from unregistering events from other plugins?
* I recommend we do away with an explicit Handled property and simply have events return `ValueTask<bool>`. If `true` is returned, the event was handled. If false, downstream handlers should handle it. This can be handy for things like logging plugins that want to see that a player said a certain thing, but don't want to prevent the player from sending the message.
* How do we handle priority? Say we have two plugins which handle chat messages - a chat plugin and a word filter. If the chat plugin handles an event first, cancels the event, and resends the chat message on a ranged channel, then the word filter may never even see the chat message to know to filter it. Some systems handle this with early/late handlers - the chat filter could register as an early event handler, the channel plugin could register as a normal event, and a placeholder plugin could register as a late event handler, modifying the text of the message to replace placeholder strings inserted by previous steps.

**Comment by Tides** [comment]
Closing as we decided/implemented a new event system.
