### ISSUE TITLE
Editing view is no longer showing the table preview

### ISSUE THREAD

**Issue by edrichhans** [ObsidianMC/Obsidian#366]
Hi! When I create a table, it used to automatically show me the formatted table even when I'm in the editor view like so:
<img width="248" alt="image" src="https://github.com/ObsidianMC/Obsidian/assets/13763624/0afd071d-5120-4956-9b59-8a705b7e3759">

But now, it just stays in the raw text. So I would have to click the `Reading view` to see my tables.

## Past behavior (ideal)

Given I'm in the editor view
And I create a table
When I select out of the table
Then the table is shown in the formatted manner

## Current behavior

Given I'm in the editor view
And I create a table
When I select out of the table
Then the table still shows the raw text

## Version
1.3.5 

## Screenshots

This is the latest version
<img width="332" alt="SCR-20230605-llyp" src="https://github.com/ObsidianMC/Obsidian/assets/13763624/c420c215-3874-4639-9bb7-7f19c371a93d">

**Comment by Tides** [comment]
Seems like you got us confused with obsidian.md 😅 go to https://forum.obsidian.md/c/bug-reports/7 for bug reports

**Comment by edrichhans** [comment]
Oh my, my. So sorry for the confusion @Tides 🤣 Thanks for pointing me in the right direction

**Comment by Naamloos** [comment]
for a moment I thought this was about crafting tables, which made me confused as we haven't implemented crafting yet.
