### ISSUE TITLE
Obsidian freezing and lagging when opening pdf files.

### ISSUE THREAD

**Issue by Scelester** [ObsidianMC/Obsidian#379]
Recently updated obsidian to version 1.3.7.

Before the update everything was fine but now whenever i click to open pdf files in newtab it freezes.

os : Manjaro Linux

[well that was embarrassing ]

**Comment by Tides** [comment]
Seems like you got us confused with obsidian.md 😅 go to https://forum.obsidian.md/c/bug-reports/7 for bug reports
