### ISSUE TITLE
Getting rid of GlobalUsings in the source code

### ISSUE THREAD

**Issue by ghost** [ObsidianMC/Obsidian#385]
Before posting your issue; please check the following box:

- [ + ] I am aware that I am making a GitHub issue for the Obsidian that is a minecraft server, and not the Obsidian that is a Markdown editor.

--------------------

I suggest not to use GlobalUsings files in the source code anymore, every time I see it I get a little trauma.

**Comment by abzh423** [comment]
Or at least let me delete them from Obsidian.NBT
