### ISSUE TITLE
Allow configuration through ENV variables

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#407]
This would make it easier to configure Obsidian when hosting it through docker, since no files will have to be modified manually.

**Comment by Tides** [comment]
To add to this, We should make use of IConfigurationManager stuff and move away from how we currently do configuration ^ ^

**Comment by Craftplacer** [comment]
What configuration is planned? Ports only? Or *all* settings?

**Comment by Craftplacer** [comment]
(oops, thanks shithub)

**Comment by Naamloos** [comment]
if doable: all

**Comment by Naamloos** [comment]
> To add to this, We should make use of IConfigurationManager stuff and move away from how we currently do configuration ^ ^

Probably a good idea, IConfigurationManager can fetch config values from multiple sources, be it env variables, a config file, etc etc
