### ISSUE TITLE
Server crashes when closing

### ISSUE THREAD

**Issue by TheVeryStarlk** [ObsidianMC/Obsidian#430]
Before posting your issue; please check the following box:

- [X] I am aware that I am making a GitHub issue for the Obsidian that is a minecraft server, and not the Obsidian that is a Markdown editor.

--------------------
[This](https://github.com/TheVeryStarlk/Obsidian/blob/master/Obsidian/Services/PacketBroadcaster.cs#L74) & [this](https://github.com/TheVeryStarlk/Obsidian/blob/master/Obsidian/WorldData/WorldManager.cs#L60) should ignore OCEs.

**Comment by Tides** [comment]
Closing as this was fixed
