### ISSUE TITLE
Implement Player Info (player list)

### ISSUE THREAD

**Issue by Craftplacer** [ObsidianMC/Obsidian#5]
- [x] Send list of all player on login
- [x] Send implement properties (no information AFAIK)
- [x] Send changes of players that left
- [ ] Send changes of players that changed their gamemode
- [x] Send changes of players that changed their ping
- [ ] Send changes of players that changed their display name

**Comment by Naamloos** [comment]
shouldn't a player list be broadcasted on every join though?

**Comment by Naamloos** [comment]
oop nvm
