### ISSUE TITLE
Implement Plugin Message (clientbound)

### ISSUE THREAD

**Issue by Craftplacer** [ObsidianMC/Obsidian#6]
- [x] Create class
  - [x] Figure out what's the most efficient way of implementing them (plain bytes or data classes)
- [x] Implement `minecraft:brand` ("null" -> "obsidian" server branding in MC)

**Comment by Tides** [comment]
Done in https://github.com/Naamloos/Obsidian/commit/38f9aadc743457ed783f28c4c618dd64a9b2118f
