### ISSUE TITLE
Implement rudimentary player loading/saving

### ISSUE THREAD

**Issue by Jonpro03** [ObsidianMC/Obsidian#61]
https://minecraft.gamepedia.com/Player.dat_format

Saved in \<worldname>/playerdata/ as \<uuid>.dat.
Compatible w/ Minecraft player.dat files.

For a first round, serialize/deserialize gamemode (playerGameType), store spawn location.

**Comment by Tides** [comment]
1d2f5b626e1402905c63cf515d4a72c5feb76aab was pushed a while ago will be closing issue
