### ISSUE TITLE
Cross-platform (Bedrock+Java+MCPE Classic)

### ISSUE THREAD

**Issue by Craftplacer** [ObsidianMC/Obsidian#7]
This feature should be worked on after 1.12.2 has been implemented. Leaving this open for discussion etc.

**Comment by Naamloos** [comment]
Protocol differences are too big I think

**Comment by Tides** [comment]
I'm pretty sure we can make this work its a p dope idea though :eyes:

**Comment by Craftplacer** [comment]
> 
> 
> Protocol differences are too big I think

I never said that we're going to use the same protocol. We only need to have a Minecraft data set and translate it for the different protocols.

**Comment by Naamloos** [comment]
Dropping this issue as it appears unreasonable to support yet another protocol when java itself has taken almost 3 years. 
Linking to [Geyser](https://geysermc.org/) too as it adds bedrock protocol support in a proxy layer.
