### ISSUE TITLE
Implement RCON abilities

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#82]
The current console does not support user input. I don't think we'll ever implement this, because we run multiple servers on one console. A different option is implementing Minecraft's RCON protocol, so we can communicate with one specific server remotely.

https://wiki.vg/RCON

Hacktoberfest edit: welcome! Feel free to tackle this issue if you feel like it. The RCON protocol would have to be it's own class that is able to accept connections and interact with the console in/output from Obsidian. Good luck!

**Comment by Naamloos** [comment]
If we implement RCON, we could maybe add an `[NoRcon]` attribute to mark commands that can and will not be executed via RCON.

**Comment by Naamloos** [comment]
Suggestion for if we _do_ implement console input:

Add a `.switch` command (that can only be executed via the console) to switch to a different server's console.

**Comment by roxxel** [comment]
We _should_ also add attributes to mark which command can only be executed by the client/console(rcon)
`[OnlyClient]` & `[OnlyConsole]`

**Comment by Craftplacer** [comment]
To allow more flexibility a [IssuerScope] attribute could be useful with a accompanying flags-enum with values like `None`, `Client`, `Console`, `RemoteConsole`, `Plugin` (plugin issued command) and finally `All = Client | Console | RemoteConsole...`.

In addition, a config entry probably would be advantage to server admins.

**Comment by roxxel** [comment]
> To allow more flexibility a [IssuerScope] attribute could be useful with a accompanying flags-enum with values like `None`, `Client`, `Console`, `RemoteConsole`, **Plugin** (plugin issued command) and finally `All = Client | Console | RemoteConsole...`.
> 
> In addition, a config entry probably would be advantage to server admins.

Plugins can't execute commands, can they?

**Comment by Craftplacer** [comment]
> > To allow more flexibility a [IssuerScope] attribute could be useful with a accompanying flags-enum with values like `None`, `Client`, `Console`, `RemoteConsole`, **Plugin** (plugin issued command) and finally `All = Client | Console | RemoteConsole...`.
> > 
> > In addition, a config entry probably would be advantage to server admins.
> 
> Plugins can't execute commands, can they?

It's entirely theoretical but I've seen Bukkit plugins like Essentials do that.

**Comment by Czompi** [comment]
> Suggestion for if we _do_ implement console input:
> 
> Add a `.switch` command (that can only be executed via the console) to switch to a different server's console.

Also we can do like a `.execute <serverId> <command>` command to directly execute commands to a specific server.

**Comment by Aaron2550** [comment]
A command only executable via RCON that returns server statistics like CPU and/or RAM usage would be kinda useful, that way a RCON client could display these stats without having to rely on a custom plugin and/or having to parse the data from command output.

**Comment by Craftplacer** [comment]
> A command only executable via RCON that returns server statistics like CPU and/or RAM usage would be kinda useful, that way a RCON client could display these stats without having to rely on a custom plugin and/or having to parse the data from command output.

I don't entirely know why this should be *only* accessible over RCON. Besides that, I think it should be possible to override server commands (that Obsidian provides commands may be nice but maybe not everyone likes them), any thoughts on that?

**Comment by Aaron2550** [comment]
> I don't entirely know why this should be _only_ accessible over RCON.

Well i mean theres no real reason to make those commands RCON only, but if a player/console executes the command it should maybe return more than just a number, "Memory Usage: 7.71GB / 8GB" or something like that.

**Comment by Aaron2550** [comment]
Quick note: Like wiki.vg says: The Character used for Color Codes (§) isnt in ASCII. Im not sure if this will be a Problem if a User sends a Command to the Server that contains a §, so i suppose we should either add:

- A Command that lets the Server know the RCON Client is able to and wants to switch to Unicode
or
- Always use the Latin1 Charset
or maybe something else i cant think of right now?

Maybe this wont even be a Problem and im just overthinking this, i just wnated to note this here.

![image](https://user-images.githubusercontent.com/24834067/135923024-ad0823ce-0443-4d31-b127-26595b45e281.png)

**Comment by Craftplacer** [comment]
> Quick note: Like wiki.vg says: The Character used for Color Codes (§) isnt in ASCII. Im not sure if this will be a Problem if a User sends a Command to the Server that contains a §, so i suppose we should either add:
> 
> * A Command that lets the Server know the RCON Client is able to and wants to switch to Unicode
>   or
> * Always use the Latin1 Charset
>   or maybe something else i cant think of right now?
> 
> Maybe this wont even be a Problem and im just overthinking this, i just wnated to note this here.
> 
> ![image](https://user-images.githubusercontent.com/24834067/135923024-ad0823ce-0443-4d31-b127-26595b45e281.png)

I don't know if RCON is supposed to be a "remote terminal protocol", in this case I'd send [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters).

**Comment by Naamloos** [comment]
It is.
